tenderIT/TenderITApp/urls.py
from django.conf.urls import url
from django.conf import  settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import (login, logout, password_change, password_change_done, password_reset, password_reset_done, password_reset_confirm, password_reset_complete)
from .views import (content_views, rgstr_views)


# content related urls
urlpatterns = [
    url(r'^$', content_views.index, name="index"),
    url(r'^company/(?P<company_id>[\w\-]+)/$', content_views.company, name="company"),
	url(r'^project/(?P<project_pk>[\w\-]+)/$', content_views.project, name="project"),
	url(r'^project/(?P<project_pk>[\w\-]+)/edit/$', content_views.project_edit, name="project-edit"),
    url(r'^project/(?P<project_pk>[\w\-]+)/delete/$',content_views.delete_project, name="delete-project"),
    url(r'^projects/all/$', content_views.project_list, name="projects"),
    url(r'^companies/$', content_views.companies, name="companies"),
    url(r'^post_project/$', content_views.post_project, name="post_project"),
    url(r'^project/(?P<project_id>[0-9]+)/apply/$', content_views.apply_project, name="apply_project"),
	url(r'^my_projects/$', content_views.my_projects, name="my_projects"),
	url(r'^my_applications/$', content_views.my_applications, name="my_applications"),
	url(r'^my_applications/(?P<application_id>[0-9]+)/edit/$', content_views.application_edit, name="application_edit"),
    url(r'^update_decription/(?P<company_id>[\w\-]+)/$', content_views.update_company_desc, name="update"),
    url(r'^ajax/save/$', content_views.save, name="save"),
    url(r'^project/(?P<project_pk>[\w\-]+)/delete/$', content_views.delete_application, name="delete-application"),
    url(r'^search/$', content_views.search, name='search'),
    url(r'^about/$', content_views.about, name="about"),
    url(r'conatact/$', content_views.contact, name="contact")
	]

# account related urls
urlpatterns += (
    url(r'^register/$', rgstr_views.register_user, name="register"),
    url(r'^login/$', login, {'template_name': 'registration/login.html'}, name="login"),
    url(r'^logged_in/$', rgstr_views.logged_in, name="logged_in"),
    url(r'^logout/$', logout,{'template_name': 'registration/log_out.html'}, name="logout"),
    url(r'^password-change/$', password_change,
        {'template_name': 'registration/password_change.html'}, name='password_change'),
    url(r'^password_change/done/$', password_change_done,
        {'template_name': 'registration/password_change_done.html'}, name='password_change_done'),
    url(r'^password-reset/$', password_reset,
        {'template_name': 'registration/password_reset.html'}, name='password_reset'),
    url(r'^password-reset/done/$', password_reset_done,
        {'template_name': 'registration/password_rst_done.html'}, name='password_reset_done'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        password_reset_confirm, {'template_name': 'registration/password_rst_confirm.html'}, name='password_reset_confirm'),
    url(r'^password-reset/complete/$', password_reset_complete,
        {'template_name': 'registration/password_rst_complete.html'}, name='password_reset_complete')
    )

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tenderIT/tenderIT/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('TenderITApp.urls')),
    url(r'^inplaceeditform/', include('inplaceeditform.urls'))
 ]

tenderIT/TenderITApp/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MaxValueValidator
from django_countries.fields import CountryField
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class Company(models.Model):
	user = models.OneToOneField(User, related_name='company')
	nationalID = models.CharField(max_length=64, validators=[MinLengthValidator(3)], unique=True)
	name = models.CharField(max_length=128, validators=[MinLengthValidator(3)])
	street = models.CharField(max_length=128)
	city = models.CharField(max_length=128)
	country = CountryField(countries_flag_url='flags/{ code }.png')
	postcode = models.CharField(max_length=16)
	email = models.EmailField()
	phone = models.CharField()
	phone = models.CharField(max_length=16)
	website = models.URLField()
	description = models.TextField(blank=True, null=True)
	logo = models.ImageField(upload_to='company_logo/%Y/%m/%d', blank=True, null=True)

	def __unicode__(self):
		return self.name

class Project(models.Model):
	company = models.ForeignKey(Company)
	title = models.CharField(max_length=128)
	description = models.TextField()
	budget = models.IntegerField()

	# Set available currency choices	
	DOLLAR = 'USD'
	EURO = 'EUR'
	POUND = 'GBP'
	CURRENCY_CHOICES = (
		(DOLLAR, 'US Dollar'),
		(EURO, 'Euro'),
		(POUND, 'British Pound'),
	)
	currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default=DOLLAR)

	startDate = models.DateField()
	endDate = models.DateField()
	publishDate = models.DateField(auto_now_add=True, null=True)
	avatar = models.ImageField(upload_to='project_avatar/%Y/%m/%d',blank=True, null=True)
	document = models.FileField(upload_to='project_document/%Y/%m/%d',blank=True, null=True)

	def __unicode__(self):
		return self.title

class Rating(models.Model):
	provider = models.ForeignKey(Company, related_name='rating_provider')
	receiver = models.ForeignKey(Company, related_name='rating_receiver')
	value = models.IntegerField(validators=[MaxValueValidator(5)])
	ratingDate = models.DateField(auto_now_add=True, null = True)

	def __unicode__(self):
		return self.receiver.name + " - " + self.provider.name

class ProjectApplication(models.Model):
	project = models.ForeignKey(Project)
	applicant = models.ForeignKey(Company, unique=True)
	price = models.IntegerField()
	description = models.TextField(blank=True, null=True)
	applicationDate = models.DateField(auto_now_add=True, null=True)
	
	# One company can have only one application for one project
	class Meta:
		unique_together = ('project','applicant')

 	def __unicode__(self):
 		return self.project.title + " - " + self.applicant.name
	

tenderIT/TenderITApp/views/content_views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from ..models import (Project,Company, ProjectApplication, Rating, )
from django.db.models import Q
from ..forms import Post_project, Apply_project
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from ..functions import ajax_login_required
from django.template.defaultfilters import escape
from django.http import HttpResponse
import re
# Home page view
def index(request):
	c = {}
	return render(request, 'index.html', c)

# All companies view, handels request for all companies, orders companies by name
def companies(request):
	company_list = Company.objects.order_by('name')	
	context_dict = {'companies' : company_list}
	return render(request, 'companies.html', context_dict)

# Single company view, handles request for a company based on company id (primary key)
def company(request, company_id):

	own_profile = False
	user = request.user

	company = get_object_or_404(Company, pk=company_id)
	if user.is_authenticated:
		try:
			if user.company:
				if user.company.pk == company.pk:
					own_profile = True
		except Exception:
			pass
	context_dict = {}
	application_list = ProjectApplication.objects.filter(applicant=company)

	# Get company by company id
	context_dict['company'] = company
	projects = Project.objects.filter(company=company)
	# Get company projects
	context_dict = {}
	try:
		context_dict['own_profile'] = own_profile
		context_dict['applications']= application_list

		# context_dict['own_profile'] = own_profile
		company = Company.objects.get(pk=company_id) 		# Get company by company id
		context_dict['company'] = company		
		projects = Project.objects.filter(company=company)  # Get company projects
		context_dict['projects'] = projects	
	# Company does not exist, do nothing
	except Company.DoesNotExist:
		pass

	return render(request, 'company_profile.html', context_dict)


# All projects view, handels request for all projects, orders projects by publish date.
def projects(request):
	project_list = Project.objects.order_by('publishDate')
	context_dict = {'projects' : project_list}	
	return render(request, 'projects.html', context_dict)

	projects = Project.objects.filter(company=company)
	context_dict['projects'] = projects

	return render(request, 'company_profile.html', context_dict)


# Single project view, handles request for a project based on projects primary key

def project(request, project_pk):
	context_dict = {}
	own_project = False
	apply_exist = None
	# Variable to show does the project belong to authenticated user
	try:	
		project = Project.objects.get(pk = project_pk)  # Get project by primary key
	 
	 # If user is authenticated check is he the owner of the project and check did he already applied for this project

		if request.user.is_authenticated():
			company = Company.objects.get(user=request.user)
			if company == project.company:
				own_project = True

			try:
				apply_exist = ProjectApplication.objects.get(applicant=company, project=project)
			except ProjectApplication.DoesNotExist:
				apply_exist = None

			# Get project application for this project


		# Get project application for this project
		applications = ProjectApplication.objects.filter(project=project)
		context_dict['applications'] = applications
		context_dict['project'] = project
		context_dict['own_project'] = own_project
		context_dict['apply_exist'] = apply_exist
	# Project does not exist, do nothing

	except Project.DoesNotExist:
		pass
	
	return render(request, 'project_templates/project.html', context_dict)

# Publish new project, user must be authenticated to publish projects
@login_required
def post_project(request):
	project_added = False  # Value to tell the template is the project added.

	# If request is POST check form validity and create new project object
	if request.method == 'POST':
		project_form = Post_project(request.POST, request.FILES)
		if project_form.is_valid():
			project=project_form.save(commit=False)
			project.company = Company.objects.get(user=request.user)
			project.avatar = request.FILES['avatar']
			project.document = request.FILES['document']
			project.save()
			project_added=True	
	# Request not POST, show the form			               
	else:
		project_form = Post_project()

	context = {
        'form' : project_form,
		'project_added' : project_added
    }
	return render(request, 'project_templates/new_project.html', context)

# updates company description
def update_company_desc(request, company_id):
	if request.method == 'POST':
		company = get_object_or_404(Company, pk= company_id)
		new_description = request.POST.get('hiddeninput')
		company.description = new_description
		company.save(update_fields = ["description"])
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))




@login_required
@login_required
def project_edit(request, project_pk):
	project = get_object_or_404(Project, pk = project_pk)
	if request.method == 'POST':
		project_form = Post_project(request.POST, instance = project)
		if project_form.is_valid():
			project = project_form.save()
	else:
		project_form = Post_project(instance=project)
	context = {'form': project_form,}
	return render(request, 'project_templates/edit_project.html', context)

# deletes a project
def delete_project(request, project_pk):
	project = get_object_or_404(Project, pk = project_pk)
	if request.method == 'POST':
		project.delete()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



# Show authenticated user projects, uses the same template as for all projects    
@login_required
def my_projects(request):
	project_list = Project.objects.filter(company=request.user.company)
	context_dict = {'projects' : project_list}
	return render(request, 'projects.html', context_dict)



# Show authenticated user project applications
@login_required
def my_applications(request):
	application_list = ProjectApplication.objects.filter(applicant=request.user.company)
	context_dict = {'applications' : application_list}
	return render(request, 'applications.html', context_dict)



# Apply project view, user must be authenticated to apply for projects
@login_required
def apply_project(request, project_id):
	print project_id
	application_added = False # Value to tell the template whether the application was sucessfull
	project	= Project.objects.get(id=project_id) # Get project by project id
	# If request is POST check form validity and create new ProjectApplication
	if request.method == 'POST':
		apply_form = Apply_project(request.POST)

        	if apply_form.is_valid():
				application = apply_form.save(commit=False)
				application.project = Project.objects.get(id=project_id)
				application.applicant = Company.objects.get(user=request.user)
				application.save()
				application_added=True
				project = application.project
	    	else:
				print apply_form.errors
	# Request not POST, show the form
	else:
        	apply_form = Apply_project()

	context = {
        'form' : apply_form,
	'application_added' : application_added,
	'project' : project,
	
    }
	return render(request, 'application.html', context)


# delete application
def delete_application(request, application_id):
	application = get_object_or_404(ProjectApplication, pk = application_id)
	if request.method == "POST":
		application.delete()

	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



# edit application
@login_required
def application_edit(request, application_id):
	application = get_object_or_404(ProjectApplication, pk = application_id)
	project = application.project
	if request.method == 'POST':
		apply_form = Apply_project(request.POST, instance = application)
		if apply_form.is_valid():
			application = apply_form.save()
	else:
		apply_form = Apply_project(instance=application)
	context = {'form': apply_form,
		'project': project,
		}
	return render(request, 'application.html', context)



 # Left for better days.
@login_required
def rate_project(request, project_id):   
	return 

# get list of projects
def project_list(request):
	context_dict ={}
	projects_list = Project.objects.all().order_by('title')
	print projects_list

	context_dict['projects_list']= projects_list
	return render(request, "project_templates/projects.html", context_dict)

# search view
def search(request):
	context = {}
	if request.method == 'POST':
		q =request.POST.get('search-item')
		print q

		companies = Company.objects.filter(Q(name__icontains= q)| Q(country__icontains= q )| Q(city__icontains= q)|Q(email__icontains= q)|
										   Q(street__icontains= q)|Q(website__icontains= q)).order_by('name')
		projects = Project.objects.filter(Q(title__icontains= q))

		context ={
			'companies': companies,
			'projects': projects
		}

	return render(request, 'search.html', context)


# Ajax in place editing
def save(request):
	print "hello world"
	if request.is_ajax:
		if request.method == "POST":
			value = None
			user = request.user
			company = user.company
			if request.POST.get('id') == "company_name":
				value = request.POST.get('value')
				print value
				company.name = value
			elif request.POST.get('id') == "company_natid":
				value = request.POST.get('value')
				company.nationalID = value
			elif request.POST.get('id') == "company_country":
				value = request.POST.get('value')
				company.country = value
			elif request.POST.get('id') == "company_city":
				value = request.POST.get('value')
				company.city = value
			elif request.POST.get('id') == "company_street":
				value = request.POST.get('value')
				company.street = value
			elif request.POST.get('id') == "company_postcode":
				value = request.POST.get('value')
				company.postcode = value
			elif request.POST.get('id') == "company_email":
				value = request.POST.get('value')
				company.email = value
			elif request.POST.get('id') == "company_phone":
				value = request.POST.get('value')
				company.phone = value

tenderIT/TenderITApp/templates/about.html
{% extends 'base.html' %}

{% block body_block %}
<div id="about" class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h1 class="text-center">About TenderIt</h1>
<p class="text-justify">
    TendersIT is provided by “AMIGO” group, which was founded by Almin Vehabovic, Gadir Rustamli, Mrulani Rane and Ismayil Rzayev  in 2016.
    All founders are still actively running the company, with Ismayil Rzayev and Mrulani Rane focusing on the procurement
    issues, while Almin Vehabovic, Gadir Rustamli concentrates on the I.T. systems.
</p>

<p class="text-justify">
    TenderIT is a B2B website aimed to create a hub where people from around the world can access creative talent, and help creatives from across the globe find new customers.It connects companies with ‘needs’ who can post projects whilst companies with ‘resources’ can apply for it.
    Tender IT makes geography and title irrelevant and, thereby, opens new markets for creativity all the world over.
</p>
<p class="text-justify">
    The best companies win with the best talent.
    But great people can be hard to find. We’ve created an online website for the world – connecting companies who wants service with other companies who wants to render the service.
    “Amigo” group is focused on building one great workplace for companies who want to post projects and companies who have skills to complete such projects.
    Targeted users are all types of companies that either need some IT work or can perform some IT work.
</p>
    </div>
</div>


{% endblock %}

tenderIT/TenderITApp/templates/account_base.html
{% extends "base.html" %}
{% block body_block %}
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="background">
<div id="account-content" class="container">
	<div class="row">

				{% block content %}
				{% endblock %}
	</div>
	</div>
</div>
</body>
{% endblock %}

tenderIT/TenderITApp/templates/application.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
	
{% if application_added %}

	<div class="container">
		<h3>Successfully applied to {{project.title}}</h3>
	</div>

{% else %}
<div class="container">
	<h2 class="text-center">Please fill application details</h2>
	<hr>
	<div class="col-lg-7 col-lg-offset-1">
		<form id="apply_form" method="POST" action=".">
		{% csrf_token %}
		{% crispy form %}

	</form>
	</div>

</div>

	
{% endif %}	
{% endblock %}

tenderIT/TenderITApp/templates/applications.html
{% extends 'base.html' %}
{% block body_block %}

{% if applications %}
	   {% for application in applications %}
	   <p>
	   <a href="/project/{{ application.project.id }}">Project: {{ application.project.title }} </a>
		<ul>
			<li>Offered price: {{ application.price }} {{ application.project.currency }}</li>
			<li>Description: {{ application.description }}</li>
		</ul>
		<form action="/my_applications/{{ application.id }}/edit/">
   					<input type="submit" value="Edit">
				</form>	
	   </p>
	   {% endfor %}
	
{% else %}
	No project applications.
{% endif %}

{% endblock %}

tenderIT/TenderITApp/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load company_tags %}

<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
	<link rel="stylesheet" href="{% static "css/style.css" %}" />
	<link rel="stylesheet" href="{% static "css/JQuery UI/jquery-ui.min.css" %}" />
	<title>TenderIt</title>

</head>

<body class="base">
<div class="container-fluid">
	<nav class="navbar navbar-default navbar-fixed-top" id="bootstrap-override">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="{% url 'index' %}"><p class="navtxt">TenderIt</p></a>
        </div>
          <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li><a href="{% url 'index' %}">Home</a></li>
                  <li><a href="{% url 'post_project' %}">Post Project</a></li>

                  <!--dropdown menu-->
                  <li class="dropdown">
                      <a role="button" data-toggle="dropdown" data-target="#" href="/page.html">
                          Browse <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                          <li><a href="{% url 'projects' %}">Projects</a></li>
                          <li class="divider"></li>
                          <li><a href="{% url 'companies' %}">Companies</a></li>
                      </ul>
                  </li>
              </ul>
              <!--end of dropdown-->

              <div class="col-sm-3 col-md-3 ">
                  <form class="navbar-form" role="search" action="{% url 'search' %}" method="POST">
                      {% csrf_token %}
                      <div class="input-group">
                          <input type="text" class="form-control" placeholder="Search" name="search-item" id="search-item">
                          <div class="input-group-btn">
                              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                          </div>
                      </div>
                  </form>
              </div>
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'about' %}">About us</a></li>
                  <li><a href="{% url 'contact' %}">Contact</a></li>
                  {% if user.is_authenticated %}
                  <li class="dropdown">
                      <a role="button" data-toggle="dropdown" class="text-capitalize" href="../navbar/">{{ user }} <span class="caret"></span></a>
                      <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                          <li><a href="{% url 'company' user.company.id %}">Profile</a></li>
                          <li class="divider"></li>
                          <li><a href="{% url 'logout' %}">Log out</a></li>
                      </ul>
                  </li>
                  {% else %}
                  <li><a href="{% url 'login' %}">Login</a></li>
                  <li><a href="{% url 'register' %}">Register<span class="sr-only">(current)</span></a></li>
                  {% endif %}
              </ul>
          </div><!--/.nav-collapse -->
      </div>
    </nav>
</div>
<script src="{% static "js/jquery-2.2.1.min.js" %}"></script>
<script src="{% static "js/jquery-ui.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/script.js" %}"></script>
<script src="{% static "js/jquery.dotdotdot.min.js" %}"></script>
<script src="{% static "js/jquery.jeditable.mini.js"%}"></script>
<div class="base-content container-fluid">
<div class="col-lg-12 col-md-12">
{% block body_block %}{% endblock %}
</div>

</div>
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3">
                    <div class="row">
                        <div class="col-lg-5 col-md-5">
                            <ul>
                                <li class="first"><a href="">About us</a></li>
                                <li><a href="">What is TenderIt</a></li></li>
                                <li><a href="">Who we are</a></li></li>
                                <li><a href="">Jobs</a></li></li>
                                <li><a href="">Press</a></li></li>
                                <li><a href="">Stats</a></li></li>
                                <li><a href="">Newsletters</a></li></li>
                                <li><a href="">Spotlight</a></li></li>
                            </ul>
                        </div>
                        <div class="col-lg-5 col-md-5">
                            <ul>
                                <li class="first"><a href="">Help</a></li>
                                <li><a href="">FAQ</a></li>
                                <li><a href="">Our Rules</a></li>
                                <li><a href="">Creators</a></li>
                                <li><a href="">Trust & safety</a></li>
                                <li><a href="">Support</a></li>
                                <li><a href="">Terms of Use</a></li>
                                <li><a href="">Privacy Policy</a></li>
                                <li><a href="">Cookie Policy</a></li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

tenderIT/TenderITApp/templates/companies.html
{% extends 'base.html' %}
{% block body_block %}
{% load staticfiles %}
{% if companies %}
    <div id="companies-list" class=" container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
				<div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<h3 class="text-center">List of All Companies</h3>
					</div>
				</div>
					<div class="panel-body">
						<ul class="list-group">
							{% for company in companies %}
								<div class="list-group">
  									<a href="{% url 'company' company.id %}" class="list-group-item ">
   										 <h4 class="navy list-group-item-heading"><strong>{{company.name}}</strong></h4>
										<p class="margin-top-10 list-group-item-text">
											<ul class="list-inline">
										<li class="list-item"><strong>Projects:</strong> {{company.project_set.count}}</li>
										<li class="last list-item"><strong>Country:</strong> {{company.country}}</li>
									</ul>
										</p>
  									</a>
								</div>
							{% endfor %}
						</ul>
					</div>
			</div>

			</div>

		</div>


{% else %}
	No published projects.
{% endif %}
</div>
{% endblock %}

tenderIT/TenderITApp/templates/contact.html
{% extends 'base.html' %}
{% block body_block %}

<h1>Contact us</h1>
<h3>For any questions please do not hesitate to contact below address</h3>
<p><strong>Address:<strong>   "AMIGO" group</p>
<p>Glasgow,University Avenue G12 8QR,</p>
<p><strong>Email:</strong> info@tendetit.com</p>
<p><strong>Mob:</strong> +1417548123456</p>
<p><strong>Phone:</strong> +1417548123456</p>

{% endblock %}

tenderIT/TenderITApp/templates/new_project.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class=" project_container col-lg-12 col-md-12">
<div class="row">
			{% if project_added %}
			<h3>Project added.</h3>
			{% else %}
				<h2 class="text-center">Please fill project details.</h2>	
				
					<!-- <div class=" project_container col-lg-11 col-lg-offset-1 col-md-12"> -->
						<form class=" project_container text-center " method="POST" action="/post_project/" enctype="multipart/form-data" data-ajax="false">				
												
							{% csrf_token %}
	 						{% crispy form %}
				
						</form>
					<!-- </div> -->			
			{% endif %}
			</div>
</div>			
{% endblock %}

tenderIT/TenderITApp/templates/search.html
{% extends 'base.html' %}
{% block body_block %}
{% load staticfiles %}
<div id="search-list" class=" container">
    <div class="row">


		<!--panel for projects-->
			<div class="col-lg-5 col-md-5 col-sm-5">
				<div class="panel panel-info">
				    <div class="panel-heading">
				    	<div class="panel-title">
					    	<h3 class="text-center">Matched Projects</h3>
					    </div>
				    </div>
					<div class="panel-body">
						<ul class="list-group">
                            {% if projects %}
							{% for project in projects %}
								<div class="list-group">
  									<a href="{% url 'project' project.id %}" class="list-group-item ">
                                        <h4 class="navy list-group-item-heading"><strong>{{project.title}}</strong></h4>
										<p class="margin-top-10 list-group-item-text">
                                            <ul class="list-inline">
										       <li class="list-item"><strong>Posted By:</strong> {{project.company.name}}</li>
										       <li class="list-item"><strong>Budget:</strong> {{project.budget}} {{project.currency}}</li>
										       <li class="last list-item"><strong>Deadline:</strong> {{project.endDate}}</li>
									        </ul>
										</p>
  									</a>
								</div>
							{% endfor %}
                            {% else %}
                                <p>No matches found for projects</p>
                            {% endif %}
						</ul>
					</div>
			    </div>
            </div>

		<!--panel for companies-->
        <div class="col-lg-5 col-lg-offset-1 col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1">
            <div class="panel panel-info">
				<div class="panel-heading">
					<div class="panel-title">
						<h3 class="text-center">Matched Companies</h3>
					</div>
				</div>
					<div class="panel-body">
						<ul class="list-group">
                            {% if companies %}
							{% for company in companies %}
								<div class="list-group">
  									<a href="{% url 'company' company.id %}" class="list-group-item ">
   										 <h4 class="navy list-group-item-heading"><strong>{{company.name}}</strong></h4>
										<p class="margin-top-10 list-group-item-text">
											<ul class="list-inline">
										<li class="list-item"><strong>Projects:</strong> {{company.project_set.count}}</li>
										<li class="last list-item"><strong>Country:</strong> {{company.country}}</li>
									</ul>
										</p>
  									</a>
								</div>
							{% endfor %}
                            {% else %}
                            <p>No matches found for companies</p>
                            {% endif %}
						</ul>
                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}